#define INTEIRO 1
#define VAR 2
#define ATT 3
#define READ 4
#define WRITE 5
#define STRING 6
#define SEP 7
#define SOMA 8
#define SUB 9
#define DIV 10
#define MULT 11
#define RESTO 12
#define NUM 13
#define FINAL 14
#define PLINE 15
#define TAB 16
#define ERRO 17                                    
